
development:
  adapter: postgresql
  encoding: unicode
  database: Know-Thy-Selfie_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: Know-Thy-Selfie_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: Know-Thy-Selfie_production
  pool: 5
